from __future__ import annotations

from functools import lru_cache
from itertools import product
from typing import Iterable


DIRECTIONS: dict[str, tuple[int, int]] = {
    "A": (1, 0),   # right same y
    "B": (1, -1),  # right up
    "C": (1, 1),   # right down
    "D": (2, 0),   # skip one plane, same y
}


def row_major_index(row: int, col: int, kp: int) -> int:
    return int(row) * int(kp) + int(col)


def motif_rows(motif: tuple[str, ...], kn: int, kp: int) -> list[str]:
    return [
        "".join(motif[row_major_index(row, col, kp)] for col in range(int(kp)))
        for row in range(int(kn))
    ]


def divisors(n: int) -> list[int]:
    return [d for d in range(1, int(n) + 1) if int(n) % d == 0]


def is_perfect_inter_matching(
    motif: tuple[str, ...],
    kn: int,
    kp: int,
    directions: dict[str, tuple[int, int]] = DIRECTIONS,
) -> bool:
    """Check the 1-out/1-in inter-link terminal constraint under periodic tiling."""

    if len(motif) != int(kn) * int(kp):
        raise ValueError(f"motif length {len(motif)} != kn*kp={int(kn) * int(kp)}")

    incoming = [[0 for _ in range(int(kp))] for _ in range(int(kn))]
    for row in range(int(kn)):
        for col in range(int(kp)):
            label = motif[row_major_index(row, col, kp)]
            dp, dy = directions[label]
            target_row = (row + int(dy)) % int(kn)
            target_col = (col + int(dp)) % int(kp)
            incoming[target_row][target_col] += 1

    return all(incoming[row][col] == 1 for row in range(int(kn)) for col in range(int(kp)))


def translate_motif(motif: tuple[str, ...], kn: int, kp: int, row_shift: int, col_shift: int) -> tuple[str, ...]:
    """Shift the cell origin. Translated cells represent the same tiling."""

    return tuple(
        motif[row_major_index((row + int(row_shift)) % int(kn), (col + int(col_shift)) % int(kp), int(kp))]
        for row in range(int(kn))
        for col in range(int(kp))
    )


def canonical_motif(motif: tuple[str, ...], kn: int, kp: int) -> tuple[str, ...]:
    return min(
        translate_motif(motif, kn, kp, row_shift, col_shift)
        for row_shift in range(int(kn))
        for col_shift in range(int(kp))
    )


def tile_motif(
    small: tuple[str, ...],
    small_kn: int,
    small_kp: int,
    kn: int,
    kp: int,
) -> tuple[str, ...]:
    if int(kn) % int(small_kn) != 0 or int(kp) % int(small_kp) != 0:
        raise ValueError("small cell dimensions must divide the target cell dimensions")
    return tuple(
        small[row_major_index(row % int(small_kn), col % int(small_kp), int(small_kp))]
        for row in range(int(kn))
        for col in range(int(kp))
    )


@lru_cache(maxsize=None)
def valid_motifs(kn: int, kp: int) -> tuple[tuple[str, ...], ...]:
    """All valid motifs modulo translation, before primitive filtering."""

    labels = tuple(DIRECTIONS)
    valid = {
        canonical_motif(tuple(candidate), int(kn), int(kp))
        for candidate in product(labels, repeat=int(kn) * int(kp))
        if is_perfect_inter_matching(tuple(candidate), int(kn), int(kp))
    }
    return tuple(sorted(valid))


@lru_cache(maxsize=None)
def primitive_motifs(kn: int, kp: int) -> tuple[tuple[str, ...], ...]:
    """Valid motifs that cannot be generated by tiling a smaller rectangular cell."""

    pool = set(valid_motifs(int(kn), int(kp)))
    repeated: set[tuple[str, ...]] = set()
    for small_kn in divisors(int(kn)):
        for small_kp in divisors(int(kp)):
            if (small_kn, small_kp) == (int(kn), int(kp)):
                continue
            for small in valid_motifs(small_kn, small_kp):
                repeated.add(
                    canonical_motif(
                        tile_motif(small, small_kn, small_kp, int(kn), int(kp)),
                        int(kn),
                        int(kp),
                    )
                )
    return tuple(sorted(pool - repeated))


def motif_edges_for_cell(
    motif: tuple[str, ...],
    kn: int,
    kp: int,
    directions: dict[str, tuple[int, int]] = DIRECTIONS,
) -> list[dict]:
    """Return one outgoing inter edge per node in the cell.

    Target row/col are not wrapped so the visualization can show which edges leave
    the displayed cell and land in a neighboring periodic copy.
    """

    edges = []
    for row in range(int(kn)):
        for col in range(int(kp)):
            label = motif[row_major_index(row, col, int(kp))]
            dp, dy = directions[label]
            edges.append(
                {
                    "src_row": int(row),
                    "src_col": int(col),
                    "dst_row": int(row + dy),
                    "dst_col": int(col + dp),
                    "direction": label,
                }
            )
    return edges


def g60_node_label(row: int, col: int, *, n_per_plane: int = 36) -> int:
    """1-based node label for the G60-style numbering in the local visualization."""

    row_mod = int(row) % int(n_per_plane)
    return int(col) * int(n_per_plane) + row_mod + 1


def summarize_motifs(motifs: Iterable[tuple[str, ...]], kn: int, kp: int) -> list[dict]:
    rows = []
    for idx, motif in enumerate(motifs, start=1):
        row_strings = motif_rows(motif, kn, kp)
        edges = motif_edges_for_cell(motif, kn, kp)
        rows.append(
            {
                "motif_id": idx,
                "kn": int(kn),
                "kp": int(kp),
                "rows": "/".join(row_strings),
                "directions": "".join(motif),
                "edges": " ".join(
                    f"{g60_node_label(edge['src_row'], edge['src_col'])}-"
                    f"{g60_node_label(edge['dst_row'], edge['dst_col'])}"
                    f"({edge['direction']})"
                    for edge in edges
                ),
            }
        )
    return rows
