# -*- coding: utf-8 -*-
"""Train a fitted-Q NumPy MLP for row-mask 000040/000056 fusion.

The input dataset contains exact Bellman Q labels generated by
``export_transition_q_value_dataset.py``. This script fits Q(t,a,b,c) and
decodes a policy by greedily taking the lowest predicted Q from each
second-order state.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any, Sequence

import numpy as np


THIS_DIR = Path(__file__).resolve().parent
if str(THIS_DIR) not in sys.path:
    sys.path.insert(0, str(THIS_DIR))

from train_transition_value_numpy_mlp_policy import (  # noqa: E402
    build_stage_matrix,
    forward,
    make_features,
    standardize_train,
    train_mlp,
)


G60_RUN_ROOT = Path(r"E:\paper11\data\satnet_experiments\runs\paper1\G60")
DEFAULT_DATASET = (
    G60_RUN_ROOT
    / "motif0040_0056_region_internal_plus_grid_transition_q_value_dataset"
    / "topk3_lam080_crit005_cnt003_build003"
    / "row_mask_transition_q_value_dataset.npz"
)
DEFAULT_OUT_DIR = G60_RUN_ROOT / "motif0040_0056_region_internal_plus_grid_fitted_q_mlp_policy"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fit a Q-value MLP and decode a row-mask fusion schedule.")
    parser.add_argument("--dataset", type=Path, default=DEFAULT_DATASET)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--target", choices=("q_value", "q_advantage"), default="q_value")
    parser.add_argument("--hidden-dim", type=int, default=192)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=4096)
    parser.add_argument("--lr", type=float, default=0.0012)
    parser.add_argument("--weight-decay", type=float, default=1e-5)
    parser.add_argument("--seed", type=int, default=668)
    parser.add_argument("--validation-mod", type=int, default=5)
    parser.add_argument("--lambda-hop", type=float, default=0.8)
    parser.add_argument("--progress-every", type=int, default=10)
    return parser.parse_args()


def mask_token(bits: np.ndarray) -> str:
    rows = [idx for idx, value in enumerate(bits.tolist()) if int(value) != 0]
    return "{" + ",".join(f"{idx:02d}" for idx in rows) + "}"


def write_rows(path: Path, rows: Sequence[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        return
    fieldnames: list[str] = []
    seen: set[str] = set()
    for row in rows:
        for key in row:
            if key not in seen:
                fieldnames.append(key)
                seen.add(key)
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def fitted_q_decode(
    *,
    steps: np.ndarray,
    time_idx: np.ndarray,
    a0: np.ndarray,
    a1: np.ndarray,
    a2: np.ndarray,
    pred_q: np.ndarray,
    stage_matrix: np.ndarray,
) -> np.ndarray:
    t_count = int(steps.size)
    order = np.argsort(time_idx, kind="stable")
    sorted_time = time_idx[order]
    offsets: dict[int, tuple[int, int]] = {}
    start = 0
    while start < order.size:
        t = int(sorted_time[start])
        end = start + 1
        while end < order.size and int(sorted_time[end]) == t:
            end += 1
        offsets[t] = (start, end)
        start = end

    start2, end2 = offsets[2]
    best_by_state: dict[tuple[int, int], tuple[float, int]] = {}
    for pos in range(start2, end2):
        idx = int(order[pos])
        state = (int(a0[idx]), int(a1[idx]))
        value = float(pred_q[idx])
        old = best_by_state.get(state)
        if old is None or value < old[0]:
            best_by_state[state] = (value, int(idx))
    initial_state = min(
        best_by_state,
        key=lambda state: float(stage_matrix[0, state[0]] + stage_matrix[1, state[1]] + best_by_state[state][0]),
    )
    selected = np.full(t_count, -1, dtype=np.int16)
    selected[0] = int(initial_state[0])
    selected[1] = int(initial_state[1])

    for t in range(2, t_count):
        if t not in offsets:
            raise ValueError(f"no transition rows at t={t}")
        start, end = offsets[t]
        best_idx: int | None = None
        best_value = float("inf")
        prev_state = (int(selected[t - 2]), int(selected[t - 1]))
        for pos in range(start, end):
            idx = int(order[pos])
            if int(a0[idx]) != prev_state[0] or int(a1[idx]) != prev_state[1]:
                continue
            value = float(pred_q[idx])
            if value < best_value:
                best_value = value
                best_idx = idx
        if best_idx is None:
            raise ValueError(f"no fitted-Q transition for t={t}, state={prev_state}")
        selected[t] = int(a2[best_idx])
    return selected


def schedule_rows(
    *,
    steps: np.ndarray,
    selected: np.ndarray,
    policy: str,
    action_names: Sequence[str],
    action_bits: np.ndarray,
    hops: np.ndarray,
    delay: np.ndarray,
    stage_matrix: np.ndarray,
    exact_selected: np.ndarray,
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for t, action_idx in enumerate(selected.astype(int).tolist()):
        bits = action_bits[int(action_idx)]
        row: dict[str, Any] = {
            "step": int(steps[t]),
            "policy": policy,
            "action": str(action_names[int(action_idx)]),
            "action_index": int(action_idx),
            "mask": mask_token(bits),
            "row_count": int(np.sum(bits)),
            "mean_hops": float(hops[t, int(action_idx)]),
            "mean_delay_ms": float(delay[t, int(action_idx)]),
            "stage_cost": float(stage_matrix[t, int(action_idx)]),
            "exact_q_action_index": int(exact_selected[t]),
            "match_exact_q_action": int(int(action_idx) == int(exact_selected[t])),
        }
        for y in range(bits.shape[0]):
            row[f"y{y:02d}"] = int(bits[y])
        rows.append(row)
    return rows


def summarize_selected(
    selected: np.ndarray,
    exact_selected: np.ndarray,
    hops: np.ndarray,
    delay: np.ndarray,
    stage_matrix: np.ndarray,
) -> dict[str, Any]:
    idx = selected.astype(int)
    row = np.arange(idx.size)
    return {
        "mean_hops_no_lst": float(np.mean(hops[row, idx])),
        "mean_delay_ms_no_lst": float(np.mean(delay[row, idx])),
        "mean_stage_cost_no_lst": float(np.mean(stage_matrix[row, idx])),
        "match_exact_q_action": float(np.mean(idx == exact_selected.astype(int))),
        "switches": int(np.count_nonzero(idx[1:] != idx[:-1])),
        "num_segments": int(np.count_nonzero(idx[1:] != idx[:-1]) + 1),
        "num_used_actions": int(len(set(int(x) for x in idx.tolist()))),
    }


def main() -> int:
    args = parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    data = np.load(Path(args.dataset), allow_pickle=True)

    steps = data["steps"].astype(np.int64)
    time_idx = data["time_index"].astype(np.int64)
    a0 = data["prev2_action_index"].astype(np.int64)
    a1 = data["prev_action_index"].astype(np.int64)
    a2 = data["action_index"].astype(np.int64)
    action_bits = data["action_bits"].astype(np.int8)
    action_names = [str(x) for x in data["action_names"].tolist()]
    hops = data["hop_table"].astype(np.float64)
    delay = data["delay_table_ms"].astype(np.float64)
    exact_selected = data["exact_selected_action_index"].astype(np.int16)
    stage_matrix = build_stage_matrix(hops, delay, float(args.lambda_hop))

    finite = np.isfinite(data[str(args.target)].astype(np.float64))
    x_raw_all = make_features(data).astype(np.float32)
    y_raw_all = data[str(args.target)].astype(np.float64)
    x_raw = x_raw_all[finite]
    y_raw = y_raw_all[finite]
    train_mask = (time_idx[finite] % int(args.validation_mod)) != 0
    x_scaled, x_mean, x_std = standardize_train(x_raw[train_mask], x_raw)
    y_mean = float(np.mean(y_raw[train_mask]))
    y_std = float(np.std(y_raw[train_mask]))
    y_std = y_std if y_std > 1e-9 else 1.0
    y_scaled = ((y_raw - y_mean) / y_std).astype(np.float32)

    params, history = train_mlp(
        x_scaled,
        y_scaled,
        train_mask,
        hidden_dim=int(args.hidden_dim),
        epochs=int(args.epochs),
        batch_size=int(args.batch_size),
        lr=float(args.lr),
        weight_decay=float(args.weight_decay),
        seed=int(args.seed),
        progress_every=int(args.progress_every),
    )
    pred_scaled, _ = forward(x_scaled, params)
    pred = pred_scaled.astype(np.float64) * y_std + y_mean
    val = ~train_mask
    val_mae = float(np.mean(np.abs(pred[val] - y_raw[val])))
    val_rmse = float(np.sqrt(np.mean((pred[val] - y_raw[val]) ** 2)))
    denom = float(np.sum((y_raw[val] - float(np.mean(y_raw[val]))) ** 2))
    val_r2 = 1.0 - float(np.sum((pred[val] - y_raw[val]) ** 2)) / max(1e-12, denom)

    pred_full = np.full(y_raw_all.shape, np.inf, dtype=np.float64)
    pred_full[np.flatnonzero(finite)] = pred
    selected = fitted_q_decode(
        steps=steps,
        time_idx=time_idx,
        a0=a0,
        a1=a1,
        a2=a2,
        pred_q=pred_full,
        stage_matrix=stage_matrix,
    )

    policy = (
        f"fitted_q_mlp_{str(args.target)}"
        f"_h{int(args.hidden_dim)}"
        f"_e{int(args.epochs)}"
        f"_lam{float(args.lambda_hop):.2f}"
    )
    schedule_path = out_dir / f"{policy}.csv"
    write_rows(
        schedule_path,
        schedule_rows(
            steps=steps,
            selected=selected,
            policy=policy,
            action_names=action_names,
            action_bits=action_bits,
            hops=hops,
            delay=delay,
            stage_matrix=stage_matrix,
            exact_selected=exact_selected,
        ),
    )
    model_path = out_dir / f"{policy}_model.npz"
    np.savez_compressed(
        model_path,
        x_mean=x_mean.astype(np.float32),
        x_std=x_std.astype(np.float32),
        y_mean=np.asarray([y_mean], dtype=np.float32),
        y_std=np.asarray([y_std], dtype=np.float32),
        **{key: value.astype(np.float32) for key, value in params.items()},
    )
    summary = {
        "policy": policy,
        "target": str(args.target),
        "dataset": str(Path(args.dataset)),
        "schedule_csv": str(schedule_path),
        "model_npz": str(model_path),
        "hidden_dim": int(args.hidden_dim),
        "epochs": int(args.epochs),
        "batch_size": int(args.batch_size),
        "lr": float(args.lr),
        "validation_mod": int(args.validation_mod),
        "lambda_hop": float(args.lambda_hop),
        "val_mae": val_mae,
        "val_rmse": val_rmse,
        "val_r2": float(val_r2),
        **summarize_selected(selected, exact_selected, hops, delay, stage_matrix),
    }
    summary_csv = out_dir / "fitted_q_mlp_policy_summary.csv"
    rows: list[dict[str, Any]] = []
    if summary_csv.exists():
        with summary_csv.open("r", encoding="utf-8-sig", newline="") as f:
            rows = list(csv.DictReader(f))
    rows.append(summary)
    write_rows(summary_csv, rows)
    meta_path = out_dir / f"{policy}_meta.json"
    meta = {
        "summary": summary,
        "history": history,
        "feature_dim": int(x_raw.shape[1]),
        "finite_samples": int(x_raw.shape[0]),
        "train_samples": int(np.count_nonzero(train_mask)),
        "validation_samples": int(np.count_nonzero(~train_mask)),
    }
    meta_path.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"summary": summary, "meta": str(meta_path)}, ensure_ascii=False, indent=2), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
