"""Parameter-transparent topology learning utilities."""

from .datasets import (
    MetricSpec,
    TopologyLearningDataset,
    WideMetricTable,
    align_metric_tables,
    build_topology_learning_dataset,
    common_topology_names,
    make_time_features,
    read_wide_metric_csv,
    write_topology_learning_dataset,
)
from .graph_state import GraphArrays, build_edge_arrays, build_node_features
from .policies import NearestNeighborPolicy, classification_report
from .full_link_gap_selector import (
    FullLinkGapMetric,
    FullLinkGapSelectionResult,
    build_full_link_gap_stage_cost,
    compute_added_edge_transition_cost,
    run_min_dwell_switch_penalty_dp,
    run_full_link_gap_selector_from_yaml,
    run_switch_penalty_dp,
)
from .budget_dp_selector import (
    BudgetDpRun,
    add_top_k_score_candidates,
    collect_candidate_actions_by_row,
    run_budget_constrained_dp,
    run_budget_constrained_frontier_dp,
    run_budget_constrained_frontier_curve_dp,
    run_budget_dp_selector,
    score_matrix_for_kind,
)
from .bridge_windows import (
    BridgeWindow,
    ScheduleSegment,
    bridge_windows_from_schedule,
    bridge_windows_from_segments,
    compress_action_segments,
    write_dataclass_rows,
)
from .lst_schedule_eval import (
    DynamicScheduleSeries,
    apply_link_setup_time_to_target_mask,
    edge_tables_from_hybrid_meta,
    evaluate_dynamic_schedule_after_lst,
    load_schedule_series_from_by_step_csv,
    load_schedule_series_from_selector,
    run_lst_evaluation_from_by_step_csv,
    run_lst_evaluation_from_selector,
    setup_command_counts_from_target_mask,
)
from .lst_aware_beam_selector import (
    LstAwareBeamResult,
    LstAwarePairSpec,
    parse_pair_spec,
    run_lst_aware_beam_selector,
)
from .link_setup_smoothing import (
    StaggeredSetupResult,
    build_deadline_aware_setup_masks,
    build_staggered_setup_masks,
    inter_port_keys_by_edge,
)
from .local_metric_replacement import (
    apply_metric_replacement,
    metric_maps_from_selector_arrays,
    read_candidate_meta_from_summary,
    read_replacement_metric_series,
    replacement_by_step_rows,
    rows_for_replacement_steps,
    setup_counts_with_local_replacement,
    summarize_local_metric_replacement,
)
from .local_replacement_ranking import (
    choose_replacement_recommendations,
    normalise_replacement_rows,
    pareto_frontier,
    read_replacement_score_rows,
    write_replacement_ranking_outputs,
)
from .post_lst_report import (
    aggregate_post_lst_summaries,
    build_decision_table,
    build_quality_tolerance_frontier,
    choose_recommendations,
    plot_pareto_report,
    write_post_lst_report,
)
from .schedule_segments import (
    build_schedule_segment_rows,
    setup_counts_from_selected_actions,
    write_schedule_segment_report,
)

__all__ = [
    "DynamicScheduleSeries",
    "FullLinkGapMetric",
    "FullLinkGapSelectionResult",
    "GraphArrays",
    "LstAwareBeamResult",
    "LstAwarePairSpec",
    "MetricSpec",
    "NearestNeighborPolicy",
    "TopologyLearningDataset",
    "WideMetricTable",
    "BridgeWindow",
    "BudgetDpRun",
    "ScheduleSegment",
    "StaggeredSetupResult",
    "align_metric_tables",
    "build_edge_arrays",
    "build_decision_table",
    "build_full_link_gap_stage_cost",
    "build_quality_tolerance_frontier",
    "build_schedule_segment_rows",
    "build_node_features",
    "build_deadline_aware_setup_masks",
    "build_staggered_setup_masks",
    "build_topology_learning_dataset",
    "bridge_windows_from_schedule",
    "bridge_windows_from_segments",
    "classification_report",
    "common_topology_names",
    "compress_action_segments",
    "compute_added_edge_transition_cost",
    "apply_link_setup_time_to_target_mask",
    "aggregate_post_lst_summaries",
    "add_top_k_score_candidates",
    "apply_metric_replacement",
    "edge_tables_from_hybrid_meta",
    "evaluate_dynamic_schedule_after_lst",
    "inter_port_keys_by_edge",
    "choose_recommendations",
    "choose_replacement_recommendations",
    "load_schedule_series_from_selector",
    "load_schedule_series_from_by_step_csv",
    "make_time_features",
    "metric_maps_from_selector_arrays",
    "parse_pair_spec",
    "plot_pareto_report",
    "read_wide_metric_csv",
    "read_candidate_meta_from_summary",
    "read_replacement_metric_series",
    "read_replacement_score_rows",
    "replacement_by_step_rows",
    "rows_for_replacement_steps",
    "normalise_replacement_rows",
    "pareto_frontier",
    "run_full_link_gap_selector_from_yaml",
    "run_budget_constrained_dp",
    "run_budget_constrained_frontier_dp",
    "run_budget_constrained_frontier_curve_dp",
    "run_budget_dp_selector",
    "run_lst_aware_beam_selector",
    "run_lst_evaluation_from_by_step_csv",
    "run_lst_evaluation_from_selector",
    "run_min_dwell_switch_penalty_dp",
    "run_switch_penalty_dp",
    "setup_command_counts_from_target_mask",
    "setup_counts_from_selected_actions",
    "setup_counts_with_local_replacement",
    "summarize_local_metric_replacement",
    "collect_candidate_actions_by_row",
    "score_matrix_for_kind",
    "write_schedule_segment_report",
    "write_dataclass_rows",
    "write_post_lst_report",
    "write_replacement_ranking_outputs",
    "write_topology_learning_dataset",
]
